### ISSUE TITLE
homer-app 7.7: knx seed:run fails with "Cannot find module '/tmp/grafana.json'"

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-app#209]
Running knx seed:run with homer-app commit 82a198f3c1b39cdda994f3717930e82edbae91cb results in the following error:

```
Using environment: development
Error: Error while executing "/opt/homer-app/seeds/99_GrafanaAPI.js" seed: Cannot find module '/tmp/grafana.json'
    at Promise.resolve.then.then.catch (/opt/homer-app/node_modules/knex/lib/seed/Seeder.js:146:25)
Error: Cannot find module '/tmp/grafana.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.seed (/opt/homer-app/seeds/99_GrafanaAPI.js:7:17)
    at Promise.resolve.then (/opt/homer-app/node_modules/knex/lib/seed/Seeder.js:143:26)
```
Indeed 99_GrafanaAPI.js includes a reference to an absolute path under /tmp where the json file is supposed to be located. Shouldn't this be included in the repo instead?

```
get grafURL = require('/tmp/grafana.json');
```

**Comment by adubovikov** [comment]
looks like this only works from installer script. For now please create an empty /tmp/grafana.json and it should be fine

**Comment by lmangani** [comment]
The temp file should be automatically created by the Grafana provisioning of a Key as a bridge in configuration. The fact is missing basically points to the Grafana API not being reachable at the time the Knex provisioning runs.

**Comment by lmangani** [comment]
Here's the failing bit: https://github.com/sipcapture/homer-app/blob/server-only/docker/docker-entrypoint.d/01-seeding_db.sh#L18

**Comment by adubovikov** [comment]
IMHO need make it by default disable. This will help everybody to use normal build

**Comment by lmangani** [comment]
I slightly disagree at this stage. If the provisioning script doesn't succeed absolutely nothing happens besides the warning error, and simply the datasource has to be configured manually.

**Comment by gedia** [comment]
FYI, an empty /tmp/grafana.json also fails with:
```
Using environment: development
Error: Error while executing "/opt/homer-app/seeds/99_GrafanaAPI.js" seed: /tmp/grafana.json: Unexpected end of JSON input
    at Promise.resolve.then.then.catch (/opt/homer-app/node_modules/knex/lib/seed/Seeder.js:146:25)
SyntaxError: /tmp/grafana.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.seed (/opt/homer-app/seeds/99_GrafanaAPI.js:7:17)
    at Promise.resolve.then (/opt/homer-app/node_modules/knex/lib/seed/Seeder.js:143:26)
```

This is with lastest master as of this writing, which is commit cbf95c5390e4472e35ff7aae02be4989c7b69205

**Comment by adubovikov** [comment]
can you upgrade to the homer-app go ?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12
