### ISSUE TITLE
Homer-app searches => 0 results after period of non-use/inactivity (docker)

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#340]
If I don't use homer for about 24 or more hours, the web interface no longer returns results (which I know to be there). Prometheus and heplify-server continue to run well in the background, and do their thing. 

If I restart e g `docker-compose kill homer-webapp ; docker-compose up -d` then searches produce results anew. 

Logs for that period `docker-compose logs -t homer-webapp` are empty. 

What more can be done? I note that logs are quite noisy when homer cannot connect to the DB e.g.:

```
...
homer-webapp      | 2020-05-02T17:02:29.514706022Z {"level":"error","msg":"dial tcp 172.16.16.10:5432: connect: connection refused","time":"2020-05-02T17:02:29Z"}
homer-webapp      | 2020-05-02T17:02:29.517021268Z panic: failed to connect database
homer-webapp      | 2020-05-02T17:02:29.517050807Z
homer-webapp      | 2020-05-02T17:02:29.517059648Z goroutine 1 [running]:
homer-webapp      | 2020-05-02T17:02:29.517066448Z main.getConfigDBSession(0xc000366290)
homer-webapp      | 2020-05-02T17:02:29.517073031Z 	/homer-app/main.go:607 +0x7c1
homer-webapp      | 2020-05-02T17:02:29.517079785Z main.main()
homer-webapp      | 2020-05-02T17:02:29.517086172Z 	/homer-app/main.go:225 +0x1b4
homer-webapp      | 2020-05-02T17:02:30.425013681Z Pre-Flight provisioning completed!
homer-webapp      | 2020-05-02T17:02:30.676387055Z
homer-webapp      | 2020-05-02T17:02:30.676422105Z CONNECT to DB ROOT STRING: [host=172.16.16.10 user=root dbname=postgres sslmode=disable port=5432 password=----]
homer-webapp      | 2020-05-02T17:02:30.676436282Z
...
```

So finding where the problem might not be so trivial.

**Comment by adubovikov** [comment]
so, the problem in the DB reconnect. Just to be sure, can you please confirm that postgres is up ?

**Comment by systemcrash** [comment]
OK, just to point out that those 'noisy' logs are from a week ago. 

DB is definitely up - but I will try restarting it *first* next time there is are no results.

**Comment by adubovikov** [comment]
@aqsyonas can you please check the reconnection or check the connection ? I.e. "SELECT 1" ?

**Comment by adubovikov** [comment]
https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime

**Comment by systemcrash** [comment]
Is there anything I can try now, that I get "no results"?

**Comment by lmangani** [comment]
@systemcrash you mean the problem has resurfaced?

**Comment by systemcrash** [comment]
Yes.

**Comment by systemcrash** [comment]
I am tailing the homer-app logs, and nothing is output while the searches get zero results (there should be data)

**Comment by systemcrash** [comment]
```shell
# docker-compose ps
       Name                     Command                  State                                                   Ports
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
alertmanager         /bin/alertmanager --config ...   Up             9093/tcp
caddy                /sbin/tini -- caddy -agree ...   Up             0.0.0.0:3000->3000/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:9093->9093/tcp
grafana              /run.sh                          Up             3000/tcp
heplify-server       ./heplify-server                 Up             0.0.0.0:9060->9060/tcp, 0.0.0.0:9060->9060/udp, 0.0.0.0:9096->9096/tcp, 0.0.0.0:9096->9096/udp
hom7-prom-all_db_1   docker-entrypoint.sh postgres    Up (healthy)   5432/tcp
homer-webapp         /docker-entrypoint.sh /hom ...   Up             0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
loki                 /usr/bin/loki -config.file ...   Up             0.0.0.0:3100->3100/tcp, 80/tcp
nodeexporter         /bin/node_exporter --path. ...   Up             9100/tcp
prometheus           /bin/prometheus --config.f ...   Up             9090/tcp
promtail             /usr/bin/promtail -config. ...   Up             0.0.0.0:1514->1514/tcp```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/pull/341

**Comment by adubovikov** [comment]
so, please recompile and re-test

**Comment by systemcrash** [comment]
How would I know that my docker image is running the new code?

**Comment by adubovikov** [comment]
if you expect to have the fix in the docker image, you should wait untill it will be released, unfortunately we don't have dev images

**Comment by systemcrash** [comment]
Is the homer-app bin file at #341 directly usable?

Not sure I can hack that in, bcz docker looks at checksums....

**Comment by lmangani** [comment]
There's no need to do that @systemcrash `docker-compose pull` will pull the latest containers you are using. If you only want to pull the homer webapp only `docker pull sipcapture/webapp:latest`

**Comment by systemcrash** [comment]
I won't know if the new version fixes the problem for at least a few days anyway. 

Pulling is no use if the changes are not yet in the docker hub. How lung until changes reflect, usually?

**Comment by lmangani** [comment]
They are there already as the container is built nightly.

**Comment by adubovikov** [comment]
I merged today, so, the nightly build will be availble tomorrow

**Comment by systemcrash** [comment]
Thanks. I'll pull tomorrow. Should know if it works in a few days.  I pulled just now, and get zero results after a restart - but it initially shows the "no data" thing which is new, so new version.  ¯\_(ツ)_/¯

**Comment by lmangani** [comment]
mmmm. Are you saying upon a restart you still have no tables created and/or data populated?

**Comment by systemcrash** [comment]
no data displays in web:

```
homer-webapp      | 2020-05-11T13:50:32.504892497Z Pre-Flight provisioning completed!
homer-webapp      | 2020-05-11T13:50:32.747107041Z
homer-webapp      | 2020-05-11T13:50:32.747142333Z CONNECT to DB ROOT STRING: [host=172.16.16.10 user=root dbname=postgres sslmode=disable port=5432 password=----]
homer-webapp      | 2020-05-11T13:50:32.747156748Z
homer-webapp      | 2020-05-11T13:50:32.763314882Z
homer-webapp      | 2020-05-11T13:50:32.763345378Z HOMER - create db [homer_config] with [name=root]
homer-webapp      | 2020-05-11T13:50:32.764081691Z
homer-webapp      | 2020-05-11T13:50:32.764094188Z (/homer-app/migration/migration.go:84)
homer-webapp      | 2020-05-11T13:50:32.764101945Z [2020-05-11 13:50:32]  pq: database "homer_config" already exists
homer-webapp      | 2020-05-11T13:50:32.764126296Z
homer-webapp      | 2020-05-11T13:50:32.764138142Z (/homer-app/migration/migration.go:84)
homer-webapp      | 2020-05-11T13:50:32.764150834Z [2020-05-11 13:50:32]  [0.75ms]  CREATE DATABASE homer_config OWNER root
homer-webapp      | 2020-05-11T13:50:32.764161409Z [0 rows affected or returned ]
homer-webapp      | 2020-05-11T13:50:32.764168503Z
homer-webapp      | 2020-05-11T13:50:32.764175386Z DONE
homer-webapp      | 2020-05-11T13:50:32.764182039Z
homer-webapp      | 2020-05-11T13:50:32.764188801Z HOMER - show users
homer-webapp      | 2020-05-11T13:50:32.764195518Z 	Role name	|	Attributes
homer-webapp      | 2020-05-11T13:50:32.764202588Z ------------------------------------------------
homer-webapp      | 2020-05-11T13:50:32.869343265Z 	homer_user	|
homer-webapp      | 2020-05-11T13:50:32.869370574Z 	root	|	superuser, create database
homer-webapp      | 2020-05-11T13:50:32.869378716Z
homer-webapp      | 2020-05-11T13:50:32.869388689Z DONE
homer-webapp      | 2020-05-11T13:50:33.104349839Z
homer-webapp      | 2020-05-11T13:50:33.104390736Z CONNECT to DB ROOT STRING: [host=172.16.16.10 user=root dbname=postgres sslmode=disable port=5432 password=----]
homer-webapp      | 2020-05-11T13:50:33.104399045Z
homer-webapp      | 2020-05-11T13:50:33.109903889Z
homer-webapp      | 2020-05-11T13:50:33.109946936Z HOMER - create db [homer_data] with [name=root]
homer-webapp      | 2020-05-11T13:50:33.110701545Z
homer-webapp      | 2020-05-11T13:50:33.110729462Z (/homer-app/migration/migration.go:84)
homer-webapp      | 2020-05-11T13:50:33.110739351Z [2020-05-11 13:50:33]  pq: database "homer_data" already exists
homer-webapp      | 2020-05-11T13:50:33.110843237Z
homer-webapp      | 2020-05-11T13:50:33.110881540Z (/homer-app/migration/migration.go:84)
homer-webapp      | 2020-05-11T13:50:33.110894011Z [2020-05-11 13:50:33]  [0.77ms]  CREATE DATABASE homer_data OWNER root
homer-webapp      | 2020-05-11T13:50:33.110901951Z [0 rows affected or returned ]
homer-webapp      | 2020-05-11T13:50:33.110908965Z
homer-webapp      | 2020-05-11T13:50:33.110917328Z DONE
homer-webapp      | 2020-05-11T13:50:33.110936789Z
homer-webapp      | 2020-05-11T13:50:33.110944394Z HOMER - show users
homer-webapp      | 2020-05-11T13:50:33.110951158Z 	Role name	|	Attributes
homer-webapp      | 2020-05-11T13:50:33.110958016Z ------------------------------------------------
homer-webapp      | 2020-05-11T13:50:33.113835853Z 	homer_user	|
homer-webapp      | 2020-05-11T13:50:33.113853313Z 	root	|	superuser, create database
homer-webapp      | 2020-05-11T13:50:33.113866457Z
homer-webapp      | 2020-05-11T13:50:33.113877722Z DONE
homer-webapp      | 2020-05-11T13:50:33.357058350Z
homer-webapp      | 2020-05-11T13:50:33.357103440Z HOMER - creating tables for the config DB [dbname=homer_config]
homer-webapp      | 2020-05-11T13:50:34.035118654Z
homer-webapp      | 2020-05-11T13:50:34.035150820Z DONE
homer-webapp      | 2020-05-11T13:50:34.291902944Z
homer-webapp      | 2020-05-11T13:50:34.291944964Z HOMER - filling tables for the config DB [dbname=homer_config]
homer-webapp      | 2020-05-11T13:50:34.291953118Z
homer-webapp      | 2020-05-11T13:50:34.291959760Z DONE
homer-webapp      | 2020-05-11T13:50:34.293909707Z Database provisioning completed!
homer-webapp      | 2020-05-11T13:50:34.536553505Z
homer-webapp      | 2020-05-11T13:50:34.536598033Z PostgreSQL version: 11.7
homer-webapp      | 2020-05-11T13:50:34.536606038Z
homer-webapp      | 2020-05-11T13:50:35.016775652Z
homer-webapp      | 2020-05-11T13:50:35.016807714Z          ___
homer-webapp      | 2020-05-11T13:50:35.016815149Z         /__/\
homer-webapp      | 2020-05-11T13:50:35.016821500Z         \  \:\
homer-webapp      | 2020-05-11T13:50:35.016828044Z          \__\:\
homer-webapp      | 2020-05-11T13:50:35.016834405Z      ___ /  /::\
homer-webapp      | 2020-05-11T13:50:35.016840670Z     /__/\  /:/\:\     _____ _____
homer-webapp      | 2020-05-11T13:50:35.016847125Z     \  \:\/:/__\/    |___  |___  |
homer-webapp      | 2020-05-11T13:50:35.016853676Z      \  \::/            / /   / /
homer-webapp      | 2020-05-11T13:50:35.016859929Z       \  \:\           / /   / /
homer-webapp      | 2020-05-11T13:50:35.016866270Z        \  \:\         /_(_) /_/
homer-webapp      | 2020-05-11T13:50:35.016872625Z         \__\/
homer-webapp      | 2020-05-11T13:50:35.016878923Z
homer-webapp      | 2020-05-11T13:50:35.016884875Z
homer-webapp      | 2020-05-11T13:50:35.016891180Z  Version: homer-app 1.1.37
homer-webapp      | 2020-05-11T13:50:35.017456827Z ⇨ http server started on [::]:80
```

**Comment by systemcrash** [comment]
Is there an environment flag I can pass to output more log/info?

**Comment by systemcrash** [comment]
(If it helps you - the last time I pulled was 2 weeks ago - and data was displaying with that build)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/440335a3a4c848ddc22858acb21a394fa6bda103
have implemented keep alive flag

**Comment by systemcrash** [comment]
> [440335a](https://github.com/sipcapture/homer-app/commit/440335a3a4c848ddc22858acb21a394fa6bda103)
> have implemented keep alive flag

Don't the docker/* files also need this treatment?

**Comment by adubovikov** [comment]
@lmangani can you please add the flag "keepalive": true , for DB connection ?

**Comment by systemcrash** [comment]
I tried adding this to my `docker-composy.yml`:
```
       - "DB_LOGLEVEL=debug"
```

No extra logging outputs.. Does this also need adding to docker-stuff?

**Comment by systemcrash** [comment]
> > [440335a](https://github.com/sipcapture/homer-app/commit/440335a3a4c848ddc22858acb21a394fa6bda103)
> > have implemented keep alive flag
> 
> Don't the docker/* files also need this treatment?
This file:
https://github.com/sipcapture/homer-app/blob/master/docker/webapp_config.json

**Comment by systemcrash** [comment]
> mmmm. Are you saying upon a restart you still have no tables created and/or data populated?

Correct - no results (no data populated).

**Comment by systemcrash** [comment]
Seems my lack of data is due also to this:

https://github.com/sipcapture/homer7-docker/issues/70

`docker-compose logs -t -f db` produced

```
db_1              | 2020-05-11T16:15:21.223670860Z 2020-05-11 16:15:21.223 UTC [39] ERROR:  no partition of relation "hep_proto_1_default" found for row
db_1              | 2020-05-11T16:15:21.223733068Z 2020-05-11 16:15:21.223 UTC [39] DETAIL:  Partition key of the failing row contains (create_date) = (2020-05-11 16:15:20.947463+00).
db_1              | 2020-05-11T16:15:21.223744125Z 2020-05-11 16:15:21.223 UTC [39] CONTEXT:  COPY hep_proto_1_default, line 1: "3bb72acb-bda5585cd1-4792258c@sipgt-6ce7448f	2020-05-11T16:15:20.947463Z	{"protocolFamily":2,"protoco..."
db_1              | 2020-05-11T16:15:21.223754022Z 2020-05-11 16:15:21.223 UTC [39] STATEMENT:  COPY hep_proto_1_default(sid,create_date,protocol_header,data_header,raw) FROM STDIN
db_1              | 2020-05-11T16:15:21.223766688Z 2020-05-11 16:15:21.223 UTC [42] ERROR:  no partition of relation "hep_proto_1_default" found for row
db_1              | 2020-05-11T16:15:21.223775392Z 2020-05-11 16:15:21.223 UTC [42] DETAIL:  Partition key of the failing row contains (create_date) = (2020-05-11 16:15:20.946787+00).
db_1              | 2020-05-11T16:15:21.223783500Z 2020-05-11 16:15:21.223 UTC [42] CONTEXT:  COPY hep_proto_1_default, line 1: "3bb72acb-bda5585cd1-4792258c@sipgt-6ce7448f	2020-05-11T16:15:20.946787Z	{"protocolFamily":2,"protoco..."
```

But those are gone after a `heplify-server` restart.

**Comment by lmangani** [comment]
@systemcrash as per above, make sure you're running the latest heplify-server container, too

**Comment by systemcrash** [comment]
Note - 'latest' can be meaningless, especially after time goes by and you're looking for `:tags` which will give you a stable combination. I've pulled in 1.30 ... 👍

**Comment by systemcrash** [comment]
> @lmangani can you please add the flag "keepalive": true , for DB connection ?

I guess I have to wait for this to go into the docker files, in the next docker build before we can investigate these changes as a fix.

**Comment by systemcrash** [comment]
Side question, but are there specific differences maintained in these two files (aside from 127.0.0.1 and e.g. loki-host)? Or can they both just use one file?

**Comment by lmangani** [comment]
@systemcrash not sure I understand - which files are you referring to? if you notice inconsistencies between examples we're excited to fix them up :)

**Comment by systemcrash** [comment]
Specifically 
https://github.com/sipcapture/homer-app/blob/master/docker/webapp_config.json 
and 
https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json

**Comment by lmangani** [comment]
Oh I get it now - one is the main config example where new features will appear, while the docker one is to be considered a preconfigured snapshot with minimal parameters and compose hosts preconfigured. It's really only used for CI and validation at this point.

**Comment by systemcrash** [comment]
OK - so the docker version must be updated as your colleague @adubovikov wrote yesterday. But by how much, I could not say.

**Comment by systemcrash** [comment]
Pushing #344 to enable keepalive toggle in docker.

**Comment by systemcrash** [comment]
Needs also #347

**Comment by systemcrash** [comment]
And #348

**Comment by systemcrash** [comment]
OK - I'm running with keepalive toggled off for, and will see how things go over the next week. Then I will try with keepalive on. There were some `heplify-server` config changes for rotation which may play a part in what was going on.

**Comment by systemcrash** [comment]
OK - things seem to be holding up after a week of use and a few days of 'non-use'. I think this problem was rooted in heplify-server's DB rotation. Apparently keepalive was: true this last week. I'll try for a week with keepalive: false

**Comment by systemcrash** [comment]
Tried also for a while including over the weekend with `keepalive: false` and things are still holding up. Seems the issue was down to rotation, which is now set. I will close the issue from my side.
